# Generated by Django 4.0.1 on 2022-01-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_rename_preo_produto_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='emial',
            new_name='email',
        ),
    ]
